#pragma once
#ifdef SNAKESANDLADDERSDEPENDENCYINVERSION_EXPORTS
#    define SNAKESANDLADDERSDEPENDENCYINVERSION_API __declspec(dllexport)
#else
#    define SNAKESANDLADDERSDEPENDENCYINVERSION_API __declspec(dllimport)
#endif